config/routes.rb
Rails.application.routes.draw do
  # Routes for members
  devise_for :members
  resources :members, only: [:index, :show], param: :slug

  resources :tasks

  resources :assignments do
    put 'mark_pending_review'
    put 'mark_in_progress'
    put 'mark_complete'
    put 'mark_failed'
  end

  resources :consequences

  resources :consequence_types

  root "home#index"
end

app/models/assignment.rb
# frozen_string_literal: true

# Assignment class
class Assignment < ApplicationRecord
  include AASM
  include CrewOwnable

  belongs_to :member
  belongs_to :task
  has_one :consequence, dependent: :destroy

  validates_presence_of :member_id, :task_id, :crew_id, :status

  accepts_nested_attributes_for :consequence

  enum status: [:in_progress, :pending_review, :complete, :failed]

  # Use a state machine to handle the transitions between an Assignment's statuses
  aasm :status, enum: true do
    state :in_progress, initial: true
    state :pending_review, :complete, :failed

    # Callback to update the Assignment anytime it's status has changed
    after_all_transitions :save_state

    # An Assignment in any state can be marked as :in_progress by a captain
    # and a member should be able to mark their assignment back to :in_progress
    # if it's current status is :pending_review (taken care of by Pundit)
    # Run the :update_in_progress callback after updating the status
    event :mark_in_progress, after: :update_in_progress do
      transitions from: [:pending_review], to: :in_progress

      transitions from: [:complete, :failed], to: :in_progress do
        guard do
          Pundit.policy(Current.member, self).mark_in_progress?
        end
      end
    end

    # An Assignment in any state can be marked as :pending_review by a captain
    # and a member should be able to make this change if it's current status
    # is :in_progress (taken care of by Pundit)
    event :mark_pending_review, after: :update_pending_review do
      transitions from: [:in_progress, :complete, :failed], to: :pending_review do
        guard do
          Pundit.policy(Current.member, self).mark_pending_review?
        end
      end
    end

    # An Assignment in any state can be marked :complete by a captain
    # Run the :update_complete callback after updating the status
    event :mark_complete, after: :update_complete do
      transitions from: [:pending_review, :in_progress, :failed], to: :complete do
        guard do
          Pundit.policy(Current.member, self).mark_complete?
        end
      end
    end

    # An Assignment in any state can be marked :failed by a captain
    # Run the :update_failed callback after updating the status
    event :mark_failed, after: :update_failed do
      transitions from: [:in_progress, :pending_review, :complete], to: :failed do
        guard do
          Pundit.policy(Current.member, self).mark_failed?
        end
      end
    end
  end

  private

  # Callback for the state machine's transition to :complete
  def update_complete
    AssignmentInteractions::UpdateComplete.run(assignment: self, member: Current.member)
  end

  # Callback for the state machine's transition to :failed
  def update_failed
    AssignmentInteractions::UpdateFailed.run(assignment: self, member: Current.member)
  end

  # Callback for the state machine's transition to :in_progress
  def update_in_progress
    AssignmentInteractions::UpdateInProgress.run(assignment: self, member: Current.member)
  end

  # Callback for the state machine's transition to :pending_review
  def update_pending_review
    AssignmentInteractions::UpdatePendingReview.run(assignment: self, member: Current.member)
  end

  # Callback for any of our state machine's transitions to ensure we always save
  # the record with the updated status
  def save_state
    self.update(status: aasm(:status).to_state)
  end
end

app/controllers/assignments_controller.rb
# frozen_string_literal: true

# Assignments controller
# Every action should be authorized via Pundit and should be captain-only
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[show edit update destroy]

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new

    authorize @assignment

    @members    = Member.all
    @tasks      = Task.all

    @assignment.build_consequence
  end

  # GET /assignments/1/edit
  def edit
    authorize @assignment

    @members = Member.all
    @tasks   = Task.all
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    authorize @asignnment

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to assignment_url(@assignment), notice: 'Member task was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        @tasks   = Task.all
        @members = Member.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    authorize @assignment

    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignment_url(@assignment), notice: 'Member task was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  # TODO: Soft delete instead
  def destroy
    authorize @assignment

    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url, status: :see_other, notice: 'Member task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /assignments/:id/mark_pending_review
  # TODO: Handle rerendering the Show view with a turbo stream
  # TODO: Handle receiving an optional note
  def mark_pending_review
    assignment = Assignment.find(params[:assignment_id])

    authorize assignment

    if assignment.mark_pending_review
      data = { message: "This #{assignment.task.category.capitalize} has been marked as 'Pending Review' and is awaiting approval" }
    else
      data = { message: "There was an error updating this #{assignment.task.category.capitalize}" }
    end

    render json: data
  end

  # PUT /assignments/:id/mark_in_progress
  # TODO: Handle rerendering the Show view with a turbo stream
  # TODO: Handle receiving an optional note
  def mark_in_progress
    assignment = Assignment.find(params[:assignment_id])

    authorize assignment

    if assignment.mark_in_progress
      data = { message: "This #{assignment.task.category.capitalize} has been marked as 'In Progress'" }
    else
      data = { message: "There was an error updating this #{assignment.task.category.capitalize}" }
    end

    render json: data
  end

  # PUT /assignments/:id/mark_complete
  # TODO: Handle rerendering the Show view with a turbo stream
  # TODO: Handle receiving an optional note
  def mark_complete
    assignment = Assignment.find(params[:assignment_id])

    authorize assignment

    if assignment.mark_complete
      data = { message: "This #{assignment.task.category.capitalize} has been marked as 'Complete'" }
    else
      data = { message: "There was an error updating this #{assignment.task.category.capitalize}" }
    end

    render json: data
  end

  # PUT /assignments/:id/mark_failed
  # TODO: Handle rerendering the Show view with a turbo stream
  # TODO: Handle receiving an optional note
  def mark_failed
    assignment = Assignment.find(params[:assignment_id])

    authorize assignment

    if assignment.mark_failed
      data = { message: "This #{assignment.task.category.capitalize} has been marked as 'Failed'" }
    else
      data = { message: "There was an error updating this #{assignment.task.category.capitalize}" }
    end

    render json: data
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # Accept nested attribtues for the consequence.
  # Do not permit the 'status' attribute as we want to handle that separately
  # so we can make use of our AASM logic.
  def assignment_params
    params.require(:assignment).permit(:member_id, :task_id, :due_date, :reward,
                                       consequence_attributes: [:value,
                                                                :duration,
                                                                :category])
  end
end

app/views/assignments/_captain_update_status.html.erb
<button data-action="click->update-status#toggleCaptainModal" class="btn btn-blue">
  Update Status
</button>

<div data-target="update-status.captainModal"
     class="fixed z-10 inset-0 overflow-y-auto hidden"
     aria-labelledby="modal-title"
     role="dialog"
     aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div data-action="click->update-status#toggleCaptainModal" class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <div class="relative inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
      <div class="hidden sm:block absolute top-0 right-0 pt-4 pr-4">
        <button data-action="click->update-status#toggleCaptainModal"
                type="button"
                class="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="sr-only">Close</span>
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="sm:flex sm:items-start">
        <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full text-indigo-700 bg-indigo-100 sm:mx-0 sm:h-10 sm:w-10">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
        </div>
        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
          <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4" id="modal-title">Update Status</h3>
          <div id="update-status-modal-message-container"></div>
          <div class="sm:mt-6">
            <fieldset data-target="update-status.radioButtonFieldSet">
              <div class="bg-white rounded-md -space-y-px">
              <!-- TODO: apply styles to whatever option is selected -->
                <!-- Checked: "bg-indigo-50 border-indigo-200 z-10", Not Checked: "border-gray-200" -->
                <label class="rounded-tl-md rounded-tr-md relative border p-4 flex cursor-pointer focus:outline-none">
                  <input type="radio" name="selected-status" value="in_progress" class="h-4 w-4 mt-0.5 cursor-pointer text-indigo-600 border-gray-300 focus:ring-indigo-500" aria-labelledby="privacy-setting-0-label" aria-describedby="privacy-setting-0-description">
                  <div class="ml-3 flex flex-col">
                    <!-- Checked: "text-indigo-900", Not Checked: "text-gray-900" -->
                    <span id="privacy-setting-0-label" class="block text-sm font-bold"> In Progress </span>
                    <!-- Checked: "text-indigo-700", Not Checked: "text-gray-500" -->
                    <span id="privacy-setting-0-description" class="block text-sm"> This task isn't done, but there is still an opportunity to complete it. </span>
                  </div>
                </label>

                <label class="relative border p-4 flex cursor-pointer focus:outline-none">
                  <input type="radio" name="selected-status" value="complete" class="h-4 w-4 mt-0.5 cursor-pointer text-indigo-600 border-gray-300 focus:ring-indigo-500" aria-labelledby="privacy-setting-1-label" aria-describedby="privacy-setting-1-description">
                  <div class="ml-3 flex flex-col">
                    <span id="privacy-setting-1-label" class="block text-sm font-bold"> Complete </span>
                    <span id="privacy-setting-1-description" class="block text-sm"> This task is 100% complete and we should apply rewards. </span>
                  </div>
                </label>
              
                <label class="relative border p-4 flex cursor-pointer focus:outline-none">
                  <input type="radio" name="selected-status" value="pending_review" class="h-4 w-4 mt-0.5 cursor-pointer text-indigo-600 border-gray-300 focus:ring-indigo-500" aria-labelledby="privacy-setting-1-label" aria-describedby="privacy-setting-1-description">
                  <div class="ml-3 flex flex-col">
                    <span id="privacy-setting-1-label" class="block text-sm font-bold"> Pending Review </span>
                    <span id="privacy-setting-1-description" class="block text-sm"> The completion of this task still needs to be verified. </span>
                  </div>
                </label>

                <label class="rounded-bl-md rounded-br-md relative border p-4 flex cursor-pointer focus:outline-none">
                  <input type="radio" name="selected-status" value="failed" class="h-4 w-4 mt-0.5 cursor-pointer text-indigo-600 border-gray-300 focus:ring-indigo-500" aria-labelledby="privacy-setting-2-label" aria-describedby="privacy-setting-2-description">
                  <div class="ml-3 flex flex-col">
                    <span id="privacy-setting-2-label" class="block text-sm font-bold"> Failed </span>
                    <span id="privacy-setting-2-description" class="block text-sm"> This task can no longer be completed and we should apply consequences and revoke any rewards that might have been applied already. </span>
                  </div>
                </label>
              </div>
            </fieldset>
          </div>

          <!-- TODO: Setup the Stimulus controller, Rails controller, and AASM to allow for passing an optional note
                     This is a nice to have and not an MVP feature
          <div class="mt-4">
            <span class="label">Add a Note <span class="text-gray-500">(optional)</span></span>
            <%= text_area :note, :note, class: "input border" %>
          </div>
          -->

        </div>
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <button data-action="click->update-status#captainSubmitUpdate"
                type="button"
                class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:ml-3 sm:w-auto sm:text-sm">
          Submit
        </button>
        <button data-action="click->update-status#toggleCaptainModal"
                type="button"
                class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

app/views/assignments/_form.html.erb
<div class="max-w-xl">
  <%= form_with(model: assignment) do |form| %>
    <% if assignment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

        <ul>
          <% assignment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="border-b">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">Task and Member Details</h3>
        <p class="mt-1 text-sm text-gray-500">Select a task and member (required) and optionally add a due date.</p>
      </div>

      <div class="field mt-6">
        <%= form.label :member_id, class: "label" %>
        <%= form.select :member_id,
                        options_for_select(@members.collect { |u| [u.name, u.id] }, assignment.member&.id),
                        { include_blank: "" },
                        class: "form-select" %>
      </div>

      <div class="field mt-6">
        <%= form.label :task_id, class: "label" %>
        <%= form.select :task_id,
                        options_for_select(@tasks.collect { |u| [u.name, u.id] }, assignment.task&.id),
                        { include_blank: "" },
                        class: "form-select" %>
      </div>

      <div class="field mt-6">
        <%= form.label :due_date, class: "label" %>
        <%= form.date_field :due_date, class: "input" %>
      </div>

      <br/>
    </div>

    <div class="border-b">
      <div class="mt-6">
        <h3 class="text-lg leading-6 font-medium text-gray-900">Reward</h3>
        <p class="mt-1 text-sm text-gray-500">Set the amount of reward points for completing this assignment.</p>
      </div>

      <div class="flex mt-6">
        <div class="field mr-4">
          <%= form.label :reward, class: "label" %>
          <%= form.number_field :reward, class: "input" %>
        </div>
      </div>

      <br/>
    </div>

    <!-- Consequence builder -->
    <%= form.fields_for :consequence do |consequence_builder| %>
      <div class="border-b">
        <div class="mt-6">
          <h3 class="text-lg leading-6 font-medium text-gray-900">Consequence</h3>
          <p class="mt-1 text-sm text-gray-500">Select the consequence amount, duration, and type for not completing the task.</p>
        </div>

        <div class="flex w-full mt-6">
          <div class="field w-full mr-2">
            <%= consequence_builder.label :value, class: "label" %>
            <%= consequence_builder.number_field :value, class: "input" %>
          </div>

          <div class="field w-full mr-2">
            <%= consequence_builder.label :duration, class: "label" %>
            <%= consequence_builder.select :duration,
                                           options_for_select(Consequence.durations.map { |key, value| [key.titleize, Consequence.durations.key(value)] }),
                                           {},
                                           class: "input" %>
          </div>

          <div class="field w-full">
            <%= consequence_builder.label :type, class: "label" %>
            <%= consequence_builder.select :category,
                                           options_for_select(Consequence.categories.map { |key, value| [key.titleize, Consequence.categories.key(value)] }),
                                           {},
                                           class: "form-select" %>
          </div>
        </div>

        <br/>
      </div>
    <% end %>

    <div class="actions mt-4 text-right">
      <%= form.submit class: "btn btn-green cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/assignments/_status_indicator.html.erb
<div id="assignment-show-message-container" class="max-w-xl">
  <% if assignment.pending_review? %>
    <div class="notice border-container-green">
      <span class="text-green-900">
        <i class="fas fa-bell"></i></span><span class="ml-2 text-gray-700">
        This assignment is currently under review by a Captain.
      </span>
    </div>
  <% elsif assignment.failed? %>
    <div class="alert border-container-red">
      <span class="text-red-900">
        <i class="fas fa-exclamation-circle fa-lg"></i></span><span class="ml-2 text-gray-700">
        This assignment has been marked failed a Captain.
      </span>
    </div>
  <% elsif assignment.complete? %>
    <div class="notice border-container-green">
      <span class="text-green-900">
        <i class="fas fa-bell"></i></span><span class="ml-2 text-gray-700">
        This assignment has been marked complete by a Captain. Nice work!
      </span>
    </div>
  <% end %>
</div>

app/views/assignments/edit.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-xl flex justify-between">
    <h1 class="text-3xl font-black text-gray-700">Editing Assigned task</h1>
    <div class="text-red-700">
      <!-- TODO: Soft delete tasks, pop a modal (instead of using dialog box)
                 explaining that it unassigns these tasks from members, etc.
                 Also- need to get a confirm dialog box working but havent looked
                 into how that works now with turbo/Rails 7 yet -->
        <%= link_to assignment_path(@assignment), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to destroy this task?" } do %>

        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end %>
    </div>
  </div>
</div>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-7xl">
    <h1 class="text-3xl font-black text-gray-900">Assigned Tasks</h1>
  </div>
</div>

<div class="flex flex-col mb-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Task Name</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Assigned To</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
            </tr>
          </thead>
        <tbody>
          <% @assignments.each do |assignment| %>
            <!-- TODO: update with striping -->
            <!-- Even row -->
            <!-- <tr class="bg-gray-50"> -->
            <tr class="bg-white">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= link_to assignment.task.name, assignment_path(assignment) %></td>
              <td class="text-center px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= assignment.member.name %></td>
              <td class="text-center px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= assignment.status.humanize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<!-- task actions: Add task and Assign task -->
<% if current_member.captain? %>
  <div class="pb-4 text-right">
    <%= link_to "Create task", new_task_path, class: "btn btn-green mx-2" %>
    <%= link_to "Assign task", new_assignment_path, class: "btn btn-blue mx-2" %>
  </div>
<% end %>

app/views/assignments/new.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-7xl">
    <h1 class="text-3xl font-black text-gray-900">Assign a task</h1>
  </div>
</div>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<!-- TODO: Convert to turbo stream, remove the Stimulus stuff and the
           messages container -->
<div class="pt-2 pb-4">
  <div class="max-w-7xl flex align-middle">
    <%= image_tag avatar_url_for(@assignment.member, size: 50), class: "rounded-full" %>
    <h1 class="ml-2 pt-2 text-3xl font-black text-gray-900"><%= @assignment.task.name %></h1>
  </div>
</div>

<!-- TODO: Currently I am not updating this partial after a Captain changes the
           assignment's status, but when we convert to turbo stream that will
           all be taken care of for us -->
<%= render partial: 'status_indicator', locals: { assignment: @assignment } %>

<div class="max-w-xl">
  <div class="border-b">
    <div class="field mt-6">
      <div class="label">
        Task description
      </div>
      <div class="border-container">
        <%= @assignment.task.description %>
      </div>
    </div>

    <div class="field mt-6">
      <div class="label">
        Member
      </div>
      <div class="flex border-container">
        <%= @assignment.member.name %>
      </div>
    </div>

    <div class="field mt-6">
      <div class="label">
        Status
      </div>
      <div id="status-container" class="border-container">
        <%= @assignment.status.humanize %>
      </div>
    </div>

    <% if @assignment.due_date.present? %>
        <div class="field mt-6">
          <div class="label">
            Due Date
          </div>
          <div class="border-container">
            <%= @assignment.due_date %>
          </div>
        </div>
    <% end %>

    <br/>
  </div>

  <div class="border-b">
    <div class="mt-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">Reward Points</h3>
    </div>

    <div class="flex mt-6 border-container">
      <%= @assignment.reward %>
    </div>

    <br/>
  </div>

  <div class="border-b">
    <div class="mt-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">Consequence</h3>
    </div>

    <div class="flex w-full mt-6 border-container">
      <%= @assignment.consequence.pretty_consequence if @assignment.consequence %>
    </div>

    <br/>
  </div>
</div>

<!-- TODO: Handle displaying these buttons a little more elegantly
           Also want to give members the ability to mark something back to
           in progress if they realize the assignment wasnt completed correctly
           but they already submitted it for review. This will be a lot easier
           after converting this view to a turbo stream so just going to leave
           it as a TODO for now -->
<div id="update-status-buttons-container"
     data-controller="update-status"
     data-update-status-assignment-id-value="<%= @assignment.id %>"
     data-update-status-current-status-value="<%= @assignment.status %>"
     class="max-w-xl mt-6 text-right">
  <% if current_member.captain? %>
    <%= link_to 'Edit', edit_assignment_path(@assignment), class: "btn btn-gray" %>
    <%= render partial: 'captain_update_status' %>
  <% elsif @assignment.in_progress? %>
    <div data-target="update-status.memberUpdateStatusButton">
    <%= render partial: 'member_update_status', locals: { current_member: current_member, assignment: @assignment } %>
    </div>
  <% end %>
</div>