config/routes.rb
Rails.application.routes.draw do
  # Routes for members
  devise_for :members
  resources :members, only: [:index, :show], param: :slug

  resources :tasks

  resources :assignments do
    put 'mark_pending_review'
    put 'mark_in_progress'
    put 'mark_complete'
    put 'mark_failed'
  end

  resources :consequences

  resources :consequence_types

  root "home#index"
end

app/models/task.rb
# frozen_string_literal: true

# Task class
class Task < ApplicationRecord
  include CrewOwnable

  has_many :assignments, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  # TODO: Should training be a type of Task?
  #       Should we use STI here instead?
  enum category: [:chore, :challenge]

  # Return an array of (uniq) members assigned to a task
  #
  # @return [Array]
  def currently_assigned_members
    assignments.map(&:member).uniq
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Tasks Controller
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :check_if_captain, only: %i[new edit create update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  # TODO: Lets make these soft deletes, especially if we want to be able to
  #       view histories and whatnot. Use discard gem.
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description)
  end

  # TODO: Extract to application controller and document
  def check_if_captain
    current_member.captain?
  end
end

app/views/tasks/_form.html.erb
<div class="max-w-2xl">
  <%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input", placeholder: "Dishes, Walk the dog, etc." %>
    </div>

    <div class="field">
      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "input", rows: 5, placeholder: "Describe the task and all necessary steps to complete it" %>
    </div>

    <!-- TODO: Nested form to create the task with an assigned member -->

    <div class="actions mt-4 text-right">
      <%= form.submit class: "btn btn-green" %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-xl flex justify-between">
    <h1 class="text-3xl font-black text-gray-700">Editing task: <%= @task.name %></h1>
    <div class="text-red-700">
      <!-- TODO: Soft delete tasks, pop a modal (instead of using dialog box)
                 explaining that it unassigns these tasks from members, etc.
                 Also- need to get a confirm dialog box working but havent looked
                 into how that works now with turbo/Rails 7 yet -->
        <%= link_to task_path(@task), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to destroy this task?" } do %>

        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end %>

    </div>
  </div>
</div>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-7xl">
    <h1 class="text-3xl font-black text-gray-700">Tasks</h1>
  </div>
</div>

<div class="flex flex-col mb-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Assigned To</th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.each do |task| %>
            <!-- TODO: update with striping -->
            <!-- Even row -->
            <!-- <tr class="bg-gray-50"> -->
              <tr class="bg-white">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= task.name %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                  <div class="flex">
                    <% task.currently_assigned_members.each do |member| %>
                      <!-- This image_tag should be a link to a view that lists all the Assignedtasks a member
                           has for this particular task. A member can have multiple Assignedtasks for any given task
                           i.g. I have to take the trash out and have an Assignedtask for Friday, Saturday, Sunday
                           so I'll need to figure out the best way to handle this later. For now, just display the avatar
                           if the member is assigned to this task at all -->
                      <%= image_tag avatar_url_for(member, size: 40), class: "rounded-full mx-2" %>
                    <% end %>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Edit', edit_task_path(task), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- task actions: Add task and Assign task -->
<% if current_member.captain? %>
  <div class="pb-4 text-right">
    <%= link_to "Create task", new_task_path, class: "btn btn-green mx-2" %>
    <%= link_to "Assign task", new_assignment_path, class: "btn btn-blue mx-2" %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<div class="pt-2 pb-4">
  <div class="max-w-7xl">
    <h1 class="text-3xl font-black text-gray-700">New task</h1>
  </div>
</div>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>