config/routes.rb
Rails.application.routes.draw do
  # Routes for members
  devise_for :members
  resources :members, only: [:index, :show], param: :slug

  resources :tasks

  resources :assignments do
    put 'mark_pending_review'
    put 'mark_in_progress'
    put 'mark_complete'
    put 'mark_failed'
  end

  resources :consequences

  resources :consequence_types

  root "home#index"
end

app/views/layouts/_flash_notices.html.erb
<div id="notices" class="my-2 bg-white">
  <% if notice %>
    <div class="notice border-container-green"><span class="text-green-900"><i class="fas fa-bell"></i></span><span class="ml-2 text-gray-700"><%= notice %></span></div>
  <% end %>
  <% if alert %>
    <div class="alert border-container-red"><span class="text-red-900"><i class="fas fa-exclamation-circle fa-lg"></i></span><span class="ml-2 text-gray-700"><%= alert %></span></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>TheHouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

<body class="h-full">
    <div data-controller="application-layout">
      <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
      <div id="off-canvas-mobile-menu"
           class="fixed inset-0 flex z-40 md:hidden"
           role="dialog"
           aria-modal="true">

        <!-- Off-canvas menu overlay, show/hide based on off-canvas menu state
             TODO: something going on here between the way I've setup the HTML
                   and how I'm handling showing/hiding in the application_layout_on -->
        <div class="fixed inset-0 bg-gray-600 bg-opacity-75 hidden"
             aria-hidden="true"
             data-action="click->application-layout#toggleSideBar"
             data-target="application-layout.sideBarOverLay"
             data-transition-enter="ease-linear duration-300"
             data-transition-enter-start="transform opacity-0"
             data-transition-enter-end="transform opacity-100"
             data-transition-leave="ease-linear duration-300"
             data-transition-leave-start="transform opacity-100"
             data-transition-leave-end="transform opacity-0">
        </div>

        <!-- Off-canvas menu, show/hide based on off-canvas menu state -->
        <div class="relative flex-1 flex flex-col max-w-xs w-full bg-gray-800 hidden"
             data-target="application-layout.sideBar"
             data-transition-enter="ease-in-out duration-300"
             data-transition-enter-start="transform opacity-0"
             data-transition-enter-end="transform opacity-100"
             data-transition-leave="ease-in-out duration-300"
             data-transition-leave-start="transform opacity-100"
             data-transition-leave-end="transform opacity-0">

          <div class="absolute top-0 right-0 -mr-12 pt-2"
               data-target="application-layout.button"
               data-action="click->application-layout#toggleSideBar">
            <button type="button"
                    class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                    data-target="application-layout.button"
                    data-action="click->application-layout#toggleSideBar">
              <span class="sr-only">Close sidebar</span>
              <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <div class="flex-1 h-0 pt-5 pb-4 overflow-y-auto">
            <div class="flex-shrink-0 flex items-center px-4">
              <%= inline_svg_tag("the-house.svg", size: "36 * 36", class: "inline")%>
              <h3 class="font-extrabold text-white text-3xl pl-4">The House</h3>
            </div>
            <nav class="mt-5 px-2 space-y-1">
              <ul>
                <% if !member_signed_in? %>
                  <li><%= link_to "Log In", new_member_session_path %></li>
                <% elsif current_member.captain? %>
                  <li><%= active_link_to text: "Home", path: root_path %></li>
                  <li><%= active_link_to text: "Tasks", path: tasks_path %></li>
                  <li><%= active_link_to text: "Challenges", path: "#" %></li>
                  <li><%= active_link_to text: "Training", path: "#" %></li>
                  <li><%= active_link_to text: "Milestones", path: "#" %></li>
                  <li><%= active_link_to text: "Rewards", path: "#" %></li>
                  <li><%= active_link_to text: "Consequences", path: "#" %></li>
                  <li><%= active_link_to text: "Members", path: members_path %></li>
                  <!-- TODO: just sticking these in here, poorly styled, so I can click around more easily -->
                  <li><%= link_to 'Assignments', assignments_path, class: "text-white" %></li>
                  <li><%= link_to "Sign Out", destroy_member_session_path, data: { "turbo-method": :delete }, class: "text-white" %></li>
                <% else %>
                  <li><%= active_link_to text: "Home", path: root_path %></li>
                  <li><%= active_link_to text: "Tasks", path: tasks_path %></li>
                  <li><%= active_link_to text: "Challenges", path: "#" %></li>
                  <li><%= active_link_to text: "Training", path: "#" %></li>
                  <li><%= active_link_to text: "Milestones", path: "#" %></li>
                  <li><%= active_link_to text: "Rewards", path: "#" %></li>
                  <li><%= active_link_to text: "Consequences", path: "#" %></li>
                  <li><%= active_link_to text: "Members", path: members_path %></li>
                  <!-- TODO: just sticking these in here, poorly styled, so I can click around more easily -->
                  <li><%= link_to 'Assignments', assignments_path, class: "text-white" %></li>
                  <li><%= link_to "Sign Out", destroy_member_session_path, data: { "turbo-method": :delete }, class: "text-white" %></li>
                <% end %>
              </ul>
            </nav>
          </div>
          <% if member_signed_in? %>
            <div class="flex-shrink-0 flex bg-gray-700 p-4">
              <a href="#" class="flex-shrink-0 group block">
                <div class="flex items-center">
                  <div>
                    <%= image_tag avatar_url_for(current_member), class: "rounded-full" %>
                  </div>
                  <div class="ml-3">
                    <p class="text-base font-medium text-white"><%= current_member.crew.name %></p>
                    <p class="text-base font-medium text-white"><%= current_member.name %></p>
                    <p class="text-sm font-medium text-gray-400 group-hover:text-gray-300">View profile</p>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>

        <div data-action="click->application-layout#toggleSideBar" class="flex-shrink-0 w-14">
          <!-- Force sidebar to shrink to fit close icon and toggle the sidebar (open) -->
        </div>
      </div>

      <!-- Static sidebar for desktop -->
      <div class="hidden md:flex md:w-64 md:flex-col md:fixed md:inset-y-0">
        <!-- Sidebar component, swap this element with another sidebar if you like -->
        <div class="flex-1 flex flex-col min-h-0 bg-gray-800">
          <div class="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
            <div class="flex items-center flex-shrink-0 px-4">
              <%= inline_svg_tag("the-house.svg", size: "36 * 36", class: "inline")%>
              <h3 class="font-extrabold text-white text-3xl pl-4">The House</h3>
            </div>
            <nav class="mt-5 flex-1 px-2 space-y-1">
              <ul>
                <% if !member_signed_in? %>
                  <li><%= link_to "Log In", new_member_session_path %></li>
                <% elsif current_member.captain? %>
                  <li><%= active_link_to text: "Home", path: root_path %></li>
                  <li><%= active_link_to text: "Tasks", path: tasks_path %></li>
                  <li><%= active_link_to text: "Challenges", path: "#" %></li>
                  <li><%= active_link_to text: "Training", path: "#" %></li>
                  <li><%= active_link_to text: "Milestones", path: "#" %></li>
                  <li><%= active_link_to text: "Rewards", path: "#" %></li>
                  <li><%= active_link_to text: "Consequences", path: "#" %></li>
                  <li><%= active_link_to text: "Members", path: members_path %></li>
                  <!-- TODO: just sticking these in here, poorly styled, so I can click around more easily -->
                  <li><%= link_to 'Assignments', assignments_path, class: "text-white" %></li>
                  <li><%= link_to "Sign Out", destroy_member_session_path, data: { "turbo-method": :delete }, class: "text-white" %></li>
                <% else %>
                  <li><%= active_link_to text: "Home", path: root_path %></li>
                  <li><%= active_link_to text: "Tasks", path: tasks_path %></li>
                  <li><%= active_link_to text: "Challenges", path: "#" %></li>
                  <li><%= active_link_to text: "Training", path: "#" %></li>
                  <li><%= active_link_to text: "Milestones", path: "#" %></li>
                  <li><%= active_link_to text: "Rewards", path: "#" %></li>
                  <li><%= active_link_to text: "Consequences", path: "#" %></li>
                  <li><%= active_link_to text: "Members", path: members_path %></li>
                  <!-- TODO: just sticking these in here, poorly styled, so I can click around more easily -->
                  <li><%= link_to 'Assignments', assignments_path, class: "text-white" %></li>
                  <li><%= link_to "Sign Out", destroy_member_session_path, data: { "turbo-method": :delete }, class: "text-white" %></li>
                <% end %>
              </ul>
            </nav>
          </div>
          <% if member_signed_in? %>
            <div class="flex-shrink-0 flex bg-gray-700 p-4">
              <%= link_to member_path(current_member) do %>
                <div class="flex items-center">
                  <div>
                    <%= image_tag avatar_url_for(current_member), class: "rounded-full" %>
                  </div>
                  <div class="ml-3">
                    <p class="text-base font-medium text-white"><%= current_member.crew.name %></p>
                    <p class="text-sm font-medium text-white"><%= current_member.name %></p>
                    <p class="text-xs font-medium text-gray-300 group-hover:text-gray-200">View profile</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="md:pl-64 flex flex-col flex-1">
        <div class="sticky top-0 z-10 md:hidden pl-1 pt-1 sm:pl-3 sm:pt-3 bg-gray-100">
          <button type="button" class="-ml-0.5 -mt-0.5 h-12 w-12 inline-flex items-center justify-center rounded-md text-gray-500 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
            <span class="sr-only">Open sidebar</span>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>
        <main class="flex-1">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-1">
            <%= render partial: 'layouts/flash_notices' %>
            <%= yield %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>